#!/usr/bin/env bash
# Regenerate root-level AGENTS.md by inlining the skill content.
#
# Usage: ./scripts/build-agents.sh
#
# Why: Codex CLI and Cursor read AGENTS.md as project context but do not follow
# markdown links. To make the skill work for them out-of-the-box (per-project
# `git clone` install), AGENTS.md must contain the SKILL.md and persona-card
# bodies inline. This script regenerates AGENTS.md from the source-of-truth
# files in taina-explainer/.
#
# Source of truth:
#   taina-explainer/SKILL.md
#   taina-explainer/persona-card.zh.md
#   taina-explainer/persona-card.en.md
#
# Run this script after editing any of the above. Commit AGENTS.md alongside
# the source change.

set -euo pipefail

cd "$(dirname "$0")/.."

SKILL=taina-explainer/SKILL.md
ZH=taina-explainer/persona-card.zh.md
EN=taina-explainer/persona-card.en.md
OUT=AGENTS.md

for f in "$SKILL" "$ZH" "$EN"; do
  if [ ! -f "$f" ]; then
    echo "FAIL: source file $f not found" >&2
    exit 1
  fi
done

{
  cat <<'BANNER'
<!--
  AUTO-GENERATED by scripts/build-agents.sh — do not edit this file directly.
  Source of truth lives in taina-explainer/{SKILL.md,persona-card.zh.md,persona-card.en.md}.
  Re-run the build script after editing any source file.
-->

# taina

`AGENTS.md` is the conventional project-context file picked up by agents that
follow the AGENTS.md spec. This file inlines the full `taina-explainer` skill
so those agents have the workflow and persona content available without
needing to follow markdown links.

The same content lives in the source files under `taina-explainer/` for
agents and tooling that read those files directly.

---

BANNER

  echo
  echo "## Skill: SKILL.md"
  echo
  cat "$SKILL"

  echo
  echo
  echo "---"
  echo
  echo "## Persona card: persona-card.zh.md (北京太奶)"
  echo
  cat "$ZH"

  echo
  echo
  echo "---"
  echo
  echo "## Persona card: persona-card.en.md (London Nan)"
  echo
  cat "$EN"
} > "$OUT"

echo "PASS: regenerated $OUT from $SKILL + $ZH + $EN"
